version: 2.1

jobs:
  build:
    working_directory: ~/repo
    docker:
      - image: circleci/node:16.6.2
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "yarn.lock" }}
          paths:
            - ./node_modules
            - ./.next/cache
      - run:
          name: Install Dependencies
          command: yarn
      - save_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
          paths:
            - ./node_modules
            - ./.next/cache
      - run:
          name: Run Next JS Build
          command: yarn lint
