name: Build

on:
  pull_request:
    types: [closed]

jobs:
  Push_Image:
    # this job will only run if the PR has been merged
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: Make envfile
        uses: SpicyPizza/create-envfile@v1
        with:
          envkey_FIREBASE_PRIVATE_KEY: ${{ secrets.FIREBASE_PRIVATE_KEY }}
          envkey_COOKIE_SECRET_CURRENT: ${{ secrets.COOKIE_SECRET_CURRENT }}
          envkey_COOKIE_SECRET_PREVIOUS: ${{ secrets.COOKIE_SECRET_PREVIOUS }}
        file_name: .env
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: codingbolt/app:latest
          secrets: |
            "FIREBASE_PRIVATE_KEY=${{ secrets.FIREBASE_PRIVATE_KEY }}"
            "COOKIE_SECRET_CURRENT=${{ secrets.COOKIE_SECRET_CURRENT }}"
            "COOKIE_SECRET_PREVIOUS=${{ secrets.COOKIE_SECRET_PREVIOUS }}"
      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
