name: Build

on:
  pull_request:
    types: [closed]

    strategy:
      matrix:
        node-version: [12.x, 14.x, 16.x]
jobs:
  Push_Image:
    # this job will only run if the PR has been merged
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    # env:
    #   FIREBASE_PRIVATE_KEY: ${{ secrets.FIREBASE_PRIVATE_KEY }}
    #   COOKIE_SECRET_CURRENT: ${{ secrets.COOKIE_SECRET_CURRENT }}
    #   COOKIE_SECRET_PREVIOUS: ${{ secrets.COOKIE_SECRET_PREVIOUS }}
    #   NEXT_PUBLIC_API_KEY: ${{ secrets.NEXT_PUBLIC_API_KEY }}
    #   BUCKET_URL: ${{ secrets.BUCKET_URL }}
    #   BUCKET_KEY: ${{ secrets.BUCKET_KEY }}
    #   NEXT_PUBLIC_IMAGE_CDN_PATH: ${{ secrets.NEXT_PUBLIC_IMAGE_CDN_PATH }}
    steps:
      - uses: actions/checkout@v2
      - name: Create Env File
        run: |
          echo FIREBASE_PRIVATE_KEY= ${{ secrets.FIREBASE_PRIVATE_KEY }}                    > other.txt
          echo COOKIE_SECRET_CURRENT= ${{ secrets.COOKIE_SECRET_CURRENT }}                 >> other.txt
          echo COOKIE_SECRET_PREVIOUS= ${{ secrets.COOKIE_SECRET_PREVIOUS }}               >> other.txt
          echo NEXT_PUBLIC_API_KEY= ${{ secrets.NEXT_PUBLIC_API_KEY }}                     >> other.txt
          echo BUCKET_URL= ${{ secrets.BUCKET_URL }}                                       >> other.txt
          echo BUCKET_KEY= ${{ secrets.BUCKET_KEY }}                                       >> other.txt
          echo NEXT_PUBLIC_IMAGE_CDN_PATH= ${{ secrets.NEXT_PUBLIC_IMAGE_CDN_PATH }}       >> other.txt
          echo NEXT_PUBLIC_SUPABASE_ANON_KEY= ${{ secrets.NEXT_PUBLIC_SUPABASE_ANON_KEY }} >> other.txt
          echo NEXT_PUBLIC_SUPABASE_URL= ${{ secrets.NEXT_PUBLIC_SUPABASE_URL }}           >> other.txt

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: codingbolt/app:latest
          secrets-files: |
            "my_token=./other.txt"
