name: Build Pull Request
on: pull_request

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "16.x"

      # Install dependencies
      - run: yarn --frozen-lock-file

      # Build and output webpack stats to artifacts/webpack-stats.json
      - run: yarn build

      # Send webpack stats and build information to RelativeCI
      - name: Send webpack stats to RelativeCI
        uses: relative-ci/agent-action@v1.1.0
        with:
          webpackStatsFile: ./artifacts/bundle-stats.json
          key: ${{ secrets.RELATIVE_CI_KEY }}
